#!/bin/sh
if [ "$1" == "" ]
then
  echo "Usage: build <module>"
  echo "Example: build io/console"
  exit 1
fi

# Get module name
modulename="${1//\//-}"
dirname="$(dirname ${1})"

if [ "${1: -3}" != ".rs" ]
then
  filename=${1}.rs
else
  filename=${1}
  modulename="${modulename:0:-3}"
fi

if [ ! -e "${filename}" ]
then
  echo "error: implementation not found for ${modulename}"
  exit 1
fi

# Compile
existing_lib=`ls ./.libs/lib${modulename}-*.so 2> /dev/null`
if test "${filename}" -nt "${existing_lib}"
then
  rustc --lib ${filename} -L.libs

  # Add libs directory
  mkdir -p .libs

  # Remove any versions we already have (for now)
  rm -f .libs/lib${modulename}-*.so

  # Move built lib to libs
  mv "${dirname}"/*.so .libs/.
fi
