#!/bin/sh

# Get module name
modulename="${1##*/}"
dirname="$(dirname ${1})"

if [ "${1: -3}" != ".rs" ]
then
  filename=${1}.rs
else
  filename=${1}
  modulename="${modulename:0:-3}"
fi

# Compile
rustc --lib ${filename} -L libs

# Remove any versions we already have (for now)
rm -f libs/lib${modulename}*.so

# Move built lib to libs
mv "${dirname}"/*.so libs
