#!/bin/sh

# Get module name
modulename="${1##*/}"
dirname="$(dirname ${1})"

printf "Discovering ${1}... "

# Attempt to find an iface
if [ -e "../djehuty/${1}.if" ]
then
  echo "Found"
else
  echo "Not found"
fi
